all: Exercise1.class Exercise2.class Exercise3.class Exercise4.class Exercise5.class Exercise6.class Exercise7.class Exercise8.class Exercise9.class

Exercise1.class:
	javac Exercise1.java
Exercise2.class:
	javac Exercise2.java
Exercise3.class:
	javac Exercise3.java
Exercise4.class:
	javac Exercise4.java
Exercise5.class:
	javac Exercise5.java
Exercise6.class:
	javac Exercise6.java
Exercise7.class:
	javac Exercise7.java
Exercise8.class:
	javac Exercise8.java
Exercise9.class:
	javac Exercise9.java

clean:
	-rm *.class