all: ex1 ex2 ex3 ex4

ex1:
	g++ exercise1.cpp -o ex1 -lpthread
ex2:
	g++ exercise2.cpp -o ex2 -lpthread
ex3:
	g++ exercise3.cpp -o ex3 -lpthread
ex4:
	g++ exercise4.cpp -o ex4 -lpthread

clean:
	-rm -f ex1 ex2 ex3 ex4