all: ex1_1 ex1_2 ex2 ex3 ex4 ex5 ex6 ex7 ex8 ex9
ex1_1:
	gcc exercise1_1.c -o ex1_1
ex1_2:
	gcc -fopenmp exercise1_2.c -o ex1_2
ex2:
	gcc -fopenmp exercise2.c -o ex2
ex3:
	gcc -fopenmp exercise3.c -o ex3
ex4:
	gcc -fopenmp exercise4.c -o ex4
ex5:
	gcc -fopenmp exercise5.c -o ex5
ex6:
	gcc -fopenmp exercise6.c -o ex6
ex7:
	gcc -fopenmp exercise7.c -o ex7
ex8:
	gcc -fopenmp exercise8.c -o ex8
ex9:
	gcc -fopenmp exercise9.c random.c -o ex9

clean:
	-rm -f ex1_1 ex1_2 ex2 ex3 ex4 ex5 ex6 ex7 ex8 ex9